Repository liquibase/liquibase-databricks, pull requests merged in 2025-03, with the labels that each got.

#250 updated junit an junit-platform versions
  pom.xml
Labels: sdou

#258 DAT-19873. updated readme.md file
  README.md
Labels: TypeEnhancement

#257 🔧 fix(workflow): add cleanup job run back
  .github/workflows/lth.yml
Labels: skipReleaseNotes

#260 fix: add missing replaces method for Snapshot Generator
  src/main/java/liquibase/ext/databricks/snapshot/jvm/SchemaSnapshotGeneratorDatabricks.java
  src/main/java/liquibase/ext/databricks/snapshot/jvm/TableSnapshotGeneratorDatabricks.java
  src/main/java/liquibase/ext/databricks/snapshot/jvm/ViewSnapshotGeneratorDatabricks.java
Labels: TypeBug
